# Apply AddAutoGeneratedIdFields Migration to SQL Server
# For Docker/Production SQL Server deployments

Write-Host "=== Applying AddAutoGeneratedIdFields Migration (SQL Server) ===" -ForegroundColor Cyan

# Load environment variables if .env exists
$envFile = Join-Path $PSScriptRoot ".env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim()
            [Environment]::SetEnvironmentVariable($key, $value, 'Process')
        }
    }
    Write-Host "Loaded environment variables from .env" -ForegroundColor Green
}

# Get SQL Server connection details
$server = "localhost,1433"
$database = [Environment]::GetEnvironmentVariable("DB_NAME")
if (-not $database) { $database = "TradeFlowFSM" }

$password = [Environment]::GetEnvironmentVariable("SA_PASSWORD")
if (-not $password) { $password = "TradeFlow2025!" }

$migrationFile = Join-Path $PSScriptRoot "Migrations\AddAutoGeneratedIdFields.sql"

Write-Host "Server: $server" -ForegroundColor Gray
Write-Host "Database: $database" -ForegroundColor Gray

# Check if sqlcmd is available
$sqlcmd = Get-Command sqlcmd -ErrorAction SilentlyContinue

if (-not $sqlcmd) {
    Write-Host "`nsqlcmd not found!" -ForegroundColor Red
    Write-Host "Please install SQL Server Command Line Utilities" -ForegroundColor Yellow
    Write-Host "Download from: https://learn.microsoft.com/en-us/sql/tools/sqlcmd-utility" -ForegroundColor White
    
    Write-Host "`nAlternatively, run the migration manually:" -ForegroundColor Yellow
    Write-Host "1. Connect to SQL Server using SSMS or Azure Data Studio" -ForegroundColor White
    Write-Host "2. Execute the SQL in: $migrationFile" -ForegroundColor White
    exit 1
}

Write-Host "`nTesting connection to SQL Server..." -ForegroundColor Cyan

$testQuery = "SELECT @@VERSION"
$result = sqlcmd -S $server -U sa -P $password -d $database -Q $testQuery -h -1 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Host "Failed to connect to SQL Server!" -ForegroundColor Red
    Write-Host "Error: $result" -ForegroundColor Red
    Write-Host "`nPlease ensure:" -ForegroundColor Yellow
    Write-Host "  1. Docker SQL Server container is running" -ForegroundColor White
    Write-Host "  2. Password in .env is correct" -ForegroundColor White
    Write-Host "  3. Database '$database' exists" -ForegroundColor White
    exit 1
}

Write-Host "Connection successful!" -ForegroundColor Green

Write-Host "`nApplying migration from: $migrationFile" -ForegroundColor Cyan

# Execute the migration
$output = sqlcmd -S $server -U sa -P $password -d $database -i $migrationFile 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n=== Migration Applied Successfully ===" -ForegroundColor Green
    Write-Host $output -ForegroundColor Gray
    
    Write-Host "`nNew columns added:" -ForegroundColor Cyan
    Write-Host "  - Assets.AssetNumber (with index)" -ForegroundColor White
    Write-Host "  - InventoryItems.InventoryNumber (with index)" -ForegroundColor White
} else {
    Write-Host "`n=== Migration Failed ===" -ForegroundColor Red
    Write-Host $output -ForegroundColor Red
    exit 1
}

Write-Host "`nPress any key to continue..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
