# Apply AddAutoGeneratedIdFields Migration
# This script applies the database migration for AssetNumber and InventoryNumber fields

Write-Host "=== Applying AddAutoGeneratedIdFields Migration ===" -ForegroundColor Cyan

# Find SQLite database
$sqliteDb = Join-Path $PSScriptRoot "OneManVan.Web\AppData\OneManVan.db"
$migrationFile = Join-Path $PSScriptRoot "Migrations\AddAutoGeneratedIdFields_SQLite.sql"

if (-not (Test-Path $sqliteDb)) {
    Write-Host "SQLite database not found at: $sqliteDb" -ForegroundColor Yellow
    Write-Host "Checking for alternative locations..." -ForegroundColor Yellow
    
    # Try other common locations
    $altPaths = @(
        "OneManVan.Web\AppData\TradeFlow.db",
        "OneManVan.Web\AppData\Identity.db"
    )
    
    foreach ($path in $altPaths) {
        $fullPath = Join-Path $PSScriptRoot $path
        if (Test-Path $fullPath) {
            Write-Host "Found database at: $fullPath" -ForegroundColor Green
        }
    }
    
    Write-Host "`nPlease check your database location in appsettings.json" -ForegroundColor Yellow
    exit 1
}

Write-Host "Database found: $sqliteDb" -ForegroundColor Green

# Check if sqlite3 is available
$sqlite3 = Get-Command sqlite3 -ErrorAction SilentlyContinue

if (-not $sqlite3) {
    Write-Host "`nSQLite3 command-line tool not found!" -ForegroundColor Red
    Write-Host "Please install SQLite from: https://www.sqlite.org/download.html" -ForegroundColor Yellow
    Write-Host "`nAlternatively, you can apply the migration manually:" -ForegroundColor Yellow
    Write-Host "1. Open the database in DB Browser for SQLite" -ForegroundColor White
    Write-Host "2. Execute the SQL in: $migrationFile" -ForegroundColor White
    exit 1
}

Write-Host "`nApplying migration..." -ForegroundColor Cyan

# Read and execute each SQL statement
$sqlContent = Get-Content $migrationFile -Raw
$statements = $sqlContent -split ';' | Where-Object { $_.Trim() -ne '' -and -not $_.Trim().StartsWith('--') }

foreach ($statement in $statements) {
    $cleanStatement = $statement.Trim()
    if ($cleanStatement) {
        Write-Host "Executing: $($cleanStatement.Substring(0, [Math]::Min(50, $cleanStatement.Length)))..." -ForegroundColor Gray
        
        try {
            $result = sqlite3 $sqliteDb "$cleanStatement;"
            if ($LASTEXITCODE -eq 0) {
                Write-Host "  ? Success" -ForegroundColor Green
            } else {
                Write-Host "  ? Error: $result" -ForegroundColor Red
            }
        } catch {
            Write-Host "  ? Error: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
}

Write-Host "`n=== Migration Complete ===" -ForegroundColor Green
Write-Host "`nNew columns added:" -ForegroundColor Cyan
Write-Host "  - Assets.AssetNumber (with index)" -ForegroundColor White
Write-Host "  - InventoryItems.InventoryNumber (with index)" -ForegroundColor White

Write-Host "`nTo backfill existing records, uncomment and run the UPDATE statements in:" -ForegroundColor Yellow
Write-Host "  $migrationFile" -ForegroundColor White

Write-Host "`nPress any key to continue..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
