# Commit All Auto-ID and Code Review Fixes
# This script commits all changes from the current session

Write-Host "=== Committing Auto-ID Generation and Code Review Fixes ===" -ForegroundColor Cyan

# Check if we're in a git repository
if (-not (Test-Path ".git")) {
    Write-Host "Error: Not in a git repository!" -ForegroundColor Red
    exit 1
}

Write-Host "`nStaging all changes..." -ForegroundColor Yellow

# Stage all new and modified files
git add -A

Write-Host "`nCommit message:" -ForegroundColor Cyan
$commitMessage = @"
Feature: Auto-ID generation, security headers, and code review fixes

## Auto-ID Generation
- Added AssetNumber field to Asset model (AST-0001 format)
- Added InventoryNumber field to InventoryItem model (INV-0001 format)
- Fixed Product import to use ProductNumber instead of SKU
- Created EntityIdPrefixes constants class for centralized ID prefixes
- Customer and Product imports now auto-generate sequential IDs

## Database Migrations
- Created AddAutoGeneratedIdFields.sql (SQL Server)
- Created AddAutoGeneratedIdFields_SQLite.sql (SQLite)
- Added migration helper scripts (auto-detect, manual apply)
- Added indexes for AssetNumber and InventoryNumber in DbContext

## Code Review Fixes (Medium/Low Severity)
- L-001: Added Content Security Policy and security headers
- L-002: Generic error messages in ImportController (no info leakage)
- L-003: Replaced magic strings with EntityIdPrefixes constants
- L-004: Added database indexes for new ID fields
- M-001: Email validation already present (verified)
- M-003: Console logging acceptable for startup (verified)
- M-004: File validation already comprehensive (verified)

## Files Changed
### New Files:
- OneManVan.Shared/Constants/EntityIdPrefixes.cs
- Migrations/AddAutoGeneratedIdFields.sql
- Migrations/AddAutoGeneratedIdFields_SQLite.sql
- ApplyAutoIdMigration.ps1
- ApplyAutoIdMigration_SqlServer.ps1
- ApplyAutoIdMigration_Auto.ps1
- MIGRATION_GUIDE_AUTO_ID.md
- PRODUCT_SKU_FIX.md

### Modified Files:
- OneManVan.Shared/Models/Asset.cs (added AssetNumber)
- OneManVan.Shared/Models/InventoryItem.cs (added InventoryNumber)
- OneManVan.Shared/Data/OneManVanDbContext.cs (added indexes)
- OneManVan.Web/Services/Import/CsvImportService.cs (fixed Product import)
- OneManVan.Web/Controllers/ImportController.cs (generic errors)
- OneManVan.Web/Program.cs (security headers)

## Testing
- ? OneManVan.Web builds without errors
- ? Product import uses correct ProductNumber field
- ? Customer import auto-generates C-0001, C-0002, etc.
- ?? Database migration required before deployment

## Migration Required
Run one of these scripts before deploying:
- ApplyAutoIdMigration_Auto.ps1 (auto-detects database)
- ApplyAutoIdMigration.ps1 (SQLite)
- ApplyAutoIdMigration_SqlServer.ps1 (SQL Server)

Co-authored-by: GitHub Copilot <noreply@github.com>
"@

Write-Host $commitMessage -ForegroundColor Gray
Write-Host ""

# Show what will be committed
Write-Host "Files to be committed:" -ForegroundColor Yellow
git status --short

Write-Host "`n"
$confirm = Read-Host "Proceed with commit? (y/n)"

if ($confirm -eq 'y' -or $confirm -eq 'Y') {
    # Commit
    git commit -m $commitMessage
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "`n? Commit successful!" -ForegroundColor Green
        
        # Show commit
        Write-Host "`nCommit details:" -ForegroundColor Cyan
        git log -1 --stat
        
        Write-Host "`n"
        $push = Read-Host "Push to remote? (y/n)"
        
        if ($push -eq 'y' -or $push -eq 'Y') {
            Write-Host "`nPushing to origin master..." -ForegroundColor Yellow
            git push origin master
            
            if ($LASTEXITCODE -eq 0) {
                Write-Host "? Pushed successfully!" -ForegroundColor Green
            } else {
                Write-Host "? Push failed!" -ForegroundColor Red
            }
        }
    } else {
        Write-Host "`n? Commit failed!" -ForegroundColor Red
    }
} else {
    Write-Host "`nCommit cancelled." -ForegroundColor Yellow
    git reset HEAD
}

Write-Host "`nPress any key to continue..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
