# Complete Deployment Pipeline: Commit ? Push ? Deploy
# This script commits all changes, pushes to GitHub, and updates the server container

param(
    [switch]$SkipCommit,
    [switch]$SkipPush,
    [switch]$SkipDeploy,
    [string]$ServerHost = "localhost",
    [int]$ServerPort = 22,
    [string]$ServerUser = "root"
)

Write-Host "??????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host "?     Complete Deployment Pipeline - Commit ? Push ? Deploy    ?" -ForegroundColor Cyan
Write-Host "??????????????????????????????????????????????????????????????????" -ForegroundColor Cyan

# ============================================================================
# STEP 1: Commit Changes
# ============================================================================

if (-not $SkipCommit) {
    Write-Host "`n[STEP 1/3] Committing Changes..." -ForegroundColor Yellow
    Write-Host "????????????????????????????????????????????????????????????" -ForegroundColor Gray
    
    # Stage all changes
    Write-Host "Staging files..." -ForegroundColor Gray
    git add -A
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "? Failed to stage files!" -ForegroundColor Red
        exit 1
    }
    
    # Show what will be committed
    Write-Host "`nFiles to commit:" -ForegroundColor Cyan
    git status --short
    
    Write-Host ""
    $confirm = Read-Host "Proceed with commit? (y/n)"
    
    if ($confirm -eq 'y' -or $confirm -eq 'Y') {
        $commitMessage = @"
Feature: Auto-ID generation, security headers, and code review fixes

## Auto-ID Generation
- Added AssetNumber field to Asset model (AST-0001 format)
- Added InventoryNumber field to InventoryItem model (INV-0001 format)
- Fixed Product import to use ProductNumber instead of SKU
- Created EntityIdPrefixes constants class for centralized ID prefixes
- Customer and Product imports now auto-generate sequential IDs

## Database Migrations
- Created AddAutoGeneratedIdFields.sql (SQL Server)
- Created AddAutoGeneratedIdFields_SQLite.sql (SQLite)
- Added migration helper scripts (auto-detect, manual apply)
- Added indexes for AssetNumber and InventoryNumber in DbContext

## Code Review Fixes
- L-001: Added Content Security Policy and security headers
- L-002: Generic error messages in ImportController
- L-003: Replaced magic strings with EntityIdPrefixes constants
- L-004: Added database indexes for new ID fields

Co-authored-by: GitHub Copilot <noreply@github.com>
"@
        
        Write-Host "`nCommitting..." -ForegroundColor Gray
        git commit -m $commitMessage
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "? Commit successful!" -ForegroundColor Green
            git log -1 --oneline
        } else {
            Write-Host "? Commit failed!" -ForegroundColor Red
            exit 1
        }
    } else {
        Write-Host "Commit cancelled." -ForegroundColor Yellow
        git reset HEAD
        exit 0
    }
} else {
    Write-Host "[STEP 1/3] ? Skipped commit" -ForegroundColor Gray
}

# ============================================================================
# STEP 2: Push to GitHub
# ============================================================================

if (-not $SkipPush) {
    Write-Host "`n[STEP 2/3] Pushing to GitHub..." -ForegroundColor Yellow
    Write-Host "????????????????????????????????????????????????????????????" -ForegroundColor Gray
    
    # Check if there are commits to push
    $unpushed = git rev-list origin/master..master --count 2>$null
    
    if ($null -eq $unpushed -or $unpushed -eq 0) {
        Write-Host "??  No new commits to push." -ForegroundColor Gray
    } else {
        Write-Host "Pushing $unpushed commit(s) to origin/master..." -ForegroundColor Gray
        
        git push origin master
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "? Push successful!" -ForegroundColor Green
            Write-Host "Remote URL: $(git config --get remote.origin.url)" -ForegroundColor Gray
        } else {
            Write-Host "? Push failed!" -ForegroundColor Red
            exit 1
        }
    }
} else {
    Write-Host "[STEP 2/3] ? Skipped push" -ForegroundColor Gray
}

# ============================================================================
# STEP 3: Update Server Container
# ============================================================================

if (-not $SkipDeploy) {
    Write-Host "`n[STEP 3/3] Updating Server Container..." -ForegroundColor Yellow
    Write-Host "????????????????????????????????????????????????????????????" -ForegroundColor Gray
    
    $deploy = Read-Host "Deploy to server? (y/n)"
    
    if ($deploy -eq 'y' -or $deploy -eq 'Y') {
        Write-Host "`nServer Details:" -ForegroundColor Cyan
        Write-Host "  Host: $ServerHost" -ForegroundColor Gray
        Write-Host "  Port: $ServerPort" -ForegroundColor Gray
        Write-Host "  User: $ServerUser" -ForegroundColor Gray
        
        $deployScript = @"
#!/bin/bash
set -e

echo "??????????????????????????????????????????????????????????????????"
echo "?          Server Deployment - Pull & Restart Container        ?"
echo "??????????????????????????????????????????????????????????????????"

DEPLOY_DIR="/var/www/onemanvan"

if [ ! -d "\$DEPLOY_DIR" ]; then
    echo "? Deployment directory not found: \$DEPLOY_DIR"
    exit 1
fi

cd \$DEPLOY_DIR

echo ""
echo "[STEP 1/4] Stopping containers..."
docker-compose down

echo ""
echo "[STEP 2/4] Pulling latest changes from GitHub..."
git pull origin master

echo ""
echo "[STEP 3/4] Rebuilding Docker image..."
docker-compose build --no-cache onemanvan-web

echo ""
echo "[STEP 4/4] Starting containers..."
docker-compose up -d

echo ""
echo "? Deployment complete!"
echo ""
docker-compose ps
"@
        
        Write-Host "`nExecuting deployment..." -ForegroundColor Gray
        
        # Try SSH first
        $ssh = Get-Command ssh -ErrorAction SilentlyContinue
        
        if ($ssh) {
            Write-Host "Using SSH for deployment..." -ForegroundColor Gray
            
            # Create temporary script
            $tempScript = New-TemporaryFile -ErrorAction Stop
            $deployScript | Out-File -FilePath $tempScript -Encoding UTF8
            
            # Upload and execute
            scp -P $ServerPort $tempScript "${ServerUser}@${ServerHost}:/tmp/deploy.sh" 2>$null
            ssh -p $ServerPort "${ServerUser}@${ServerHost}" "chmod +x /tmp/deploy.sh && /tmp/deploy.sh"
            
            # Cleanup
            Remove-Item $tempScript -Force -ErrorAction SilentlyContinue
            
            if ($LASTEXITCODE -eq 0) {
                Write-Host "? Deployment successful!" -ForegroundColor Green
            } else {
                Write-Host "? Deployment failed!" -ForegroundColor Red
                exit 1
            }
        } else {
            Write-Host "??  SSH not available. Showing deployment script instead:" -ForegroundColor Yellow
            Write-Host $deployScript -ForegroundColor Cyan
            
            Write-Host "`nTo deploy manually, run the above script on the server at:" -ForegroundColor Yellow
            Write-Host "  ssh ${ServerUser}@${ServerHost}" -ForegroundColor White
        }
    } else {
        Write-Host "Deployment skipped." -ForegroundColor Yellow
    }
} else {
    Write-Host "[STEP 3/3] ? Skipped deployment" -ForegroundColor Gray
}

# ============================================================================
# Summary
# ============================================================================

Write-Host "`n??????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host "?                       Pipeline Complete!                      ?" -ForegroundColor Cyan
Write-Host "??????????????????????????????????????????????????????????????????" -ForegroundColor Cyan

Write-Host "`nSummary:" -ForegroundColor Yellow
Write-Host "  ? Code committed to local repository" -ForegroundColor Green
Write-Host "  ? Changes pushed to GitHub (origin/master)" -ForegroundColor Green

if (-not $SkipDeploy) {
    Write-Host "  ? Server container updated" -ForegroundColor Green
}

Write-Host "`nNext Steps:" -ForegroundColor Cyan
Write-Host "  1. Apply database migration on server:" -ForegroundColor White
Write-Host "     ./ApplyAutoIdMigration_Auto.ps1" -ForegroundColor Gray
Write-Host "  2. Test import functionality with sample CSV" -ForegroundColor White
Write-Host "  3. Verify auto-ID generation (C-0001, PROD-0001, etc.)" -ForegroundColor White

Write-Host "`nPress any key to continue..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
