-- Migration: Add Auto-Generated ID Fields
-- Date: February 2026
-- Purpose: Add AssetNumber and InventoryNumber columns for auto-ID generation

-- SQL Server Version

-- Add AssetNumber column to Assets table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('Assets') AND name = 'AssetNumber')
BEGIN
    ALTER TABLE Assets ADD AssetNumber NVARCHAR(20) NULL;
    PRINT 'Added column: Assets.AssetNumber';
END

-- Add InventoryNumber column to InventoryItems table
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('InventoryItems') AND name = 'InventoryNumber')
BEGIN
    ALTER TABLE InventoryItems ADD InventoryNumber NVARCHAR(20) NULL;
    PRINT 'Added column: InventoryItems.InventoryNumber';
END

-- Create index on AssetNumber for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Assets_AssetNumber' AND object_id = OBJECT_ID('Assets'))
BEGIN
    CREATE INDEX IX_Assets_AssetNumber ON Assets(AssetNumber);
    PRINT 'Created index: IX_Assets_AssetNumber';
END

-- Create index on InventoryNumber for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_InventoryItems_InventoryNumber' AND object_id = OBJECT_ID('InventoryItems'))
BEGIN
    CREATE INDEX IX_InventoryItems_InventoryNumber ON InventoryItems(InventoryNumber);
    PRINT 'Created index: IX_InventoryItems_InventoryNumber';
END

-- Optional: Generate numbers for existing records
-- Uncomment and run separately if you want to backfill existing records

/*
-- Backfill AssetNumber for existing assets
DECLARE @AssetCounter INT = 1;
DECLARE @AssetId INT;

DECLARE asset_cursor CURSOR FOR
SELECT Id FROM Assets WHERE AssetNumber IS NULL ORDER BY Id;

OPEN asset_cursor;
FETCH NEXT FROM asset_cursor INTO @AssetId;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE Assets 
    SET AssetNumber = CONCAT('AST-', RIGHT('0000' + CAST(@AssetCounter AS VARCHAR), 4))
    WHERE Id = @AssetId;
    
    SET @AssetCounter = @AssetCounter + 1;
    FETCH NEXT FROM asset_cursor INTO @AssetId;
END

CLOSE asset_cursor;
DEALLOCATE asset_cursor;

-- Backfill InventoryNumber for existing inventory items
DECLARE @InvCounter INT = 1;
DECLARE @InvId INT;

DECLARE inv_cursor CURSOR FOR
SELECT Id FROM InventoryItems WHERE InventoryNumber IS NULL ORDER BY Id;

OPEN inv_cursor;
FETCH NEXT FROM inv_cursor INTO @InvId;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE InventoryItems 
    SET InventoryNumber = CONCAT('INV-', RIGHT('0000' + CAST(@InvCounter AS VARCHAR), 4))
    WHERE Id = @InvId;
    
    SET @InvCounter = @InvCounter + 1;
    FETCH NEXT FROM inv_cursor INTO @InvId;
END

CLOSE inv_cursor;
DEALLOCATE inv_cursor;
*/

PRINT 'Migration complete: AddAutoGeneratedIdFields';
